### PR TITLE
Update to Node20

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by DavidBoike** [comment]
Notice the CI runs still say node16? I think you have to recompile the dist.js

**Comment by DavidBoike** [comment]
Oh I might be wrong. The warnings are mentioning the other actions in the CI.

**Comment by danielmarbach** [comment]
Yeah it is quite likely the login action. That's why I added the dependabot configuration too. Let me update that one quickly inline here.

**Comment by danielmarbach** [comment]
Even the latest login action still has that issue :(

https://github.com/Azure/login/issues/357

**Review by bording — APPROVED** [review]

**Pull request merged**
